apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-config
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://argoproj.github.io/argo-helm
  - https://github.com/anvaplus/homelab-k8s-argo-config
  - https://github.com/anvaplus/homelab-k8s-base-manifests
  - https://github.com/anvaplus/homelab-k8s-environments
  - https://github.com/anvaplus/homelab-k8s-environments-apps
  - https://charts.external-secrets.io
  - https://kubernetes-sigs.github.io/external-dns/
  - https://helm.cilium.io
  - https://1password.github.io/connect-helm-charts
  - https://metallb.github.io/metallb
  - https://traefik.github.io/charts
  - oci://quay.io/jetstack/charts/cert-manager
  - https://charts.longhorn.io/
  - https://cloudnative-pg.github.io/charts

status: {}