---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: traefik
    server: https://kubernetes.default.svc
  project: argo-config
  sources:
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      path: environments/dev/ingress/routes/http-routes/
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
