apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: "/spec/sources/1/targetRevision"
        value: "1.11.0"
      # add custom values
      - op: add
        path: "/spec/sources/1/helm/valueFiles/-"
        value: "$valuesRepo/environments/dev/longhorn/custom-values/custom-values.yaml"
    target:
      kind: Application
      name: longhorn

resources:
  - ../../../../base/longhorn/