apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argo-config
  sources:
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      path: environments/dev/ingress/metallb/
      targetRevision: HEAD
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      path: environments/dev/ingress/traefik/
      targetRevision: HEAD
    - repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
      path: environments/dev/ingress/routes/
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
