apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/secrets/

patches:
- target:
    kind: ExternalSecret
    name: argocd-secret-sso
  path: argocd-secret-sso.patch.yaml