apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: traefik
    server: https://kubernetes.default.svc
  project: argo-config
  source:
    repoURL: https://github.com/anvaplus/homelab-k8s-argo-config
    targetRevision: HEAD
    path: environments/dev/ingress/traefik/custom-values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true