apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: "/spec/sources/1/targetRevision"
        value: "0.27.1"
      # add custom values
      - op: add
        path: "/spec/sources/1/helm/valueFiles/-"
        value: "$valuesRepo/environments/dev/database/cnpg-operator/custom-values/custom-values.yaml"
    target:
      kind: Application
      name: cloudnative-pg-operator

resources:
  - ../../../../../base/database/cnpg-operator/