apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: "/spec/sources/1/targetRevision"
        value: "0.15.3"
    target:
      kind: Application
      name: metallb

resources:
  - ../../../../../base/ingress/metallb/
  - lb-config.yaml