apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cnpg-cluster.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: cnpg-cluster
    patch: |
      - op: replace
        path: /metadata/name
        value: cnpg-cluster-keycloak
      - op: replace
        path: /spec/destination/namespace
        value: keycloak
      - op: replace
        path: /spec/sources/1/helm/releaseName
        value: cnpg-cluster-keycloak