type: postgresql
mode: standalone

version:
  postgresql: "16"

cluster:
  instances: 3
  storage:
    size: 2Gi
    storageClass: "longhorn-cnpg"
  superuserSecret: keycloak-db-superuser
  initdb:
    database: keycloak
    owner: keycloak
    secret:
      name: keycloak-db-user

backups:
  enabled: false