apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: "/spec/sources/1/targetRevision"
        value: "39.0.0"
      # add custom values
      - op: add
        path: "/spec/sources/1/helm/valueFiles/-"
        value: "$valuesRepo/environments/dev/ingress/traefik/custom-values/override.values.yaml"
    target:
      kind: Application
      name: traefik

resources:
  - ../../../../../base/ingress/traefik/
